name: Read property
description: Read a property from Java properties file

inputs:
  file:
    required: true
    description: Path to properties file
  failIfFileNotFound:
    default: 'true'
    required: true
    description: Set to 'false' to return default value if the properties file can't be found
  property:
    required: true
    description: Property name
  failIfPropertyNotFound:
    default: 'true'
    required: true
    description: Set to 'true' to return default value if the property can't be found in the properties file
  defaultValue:
    required: false
    description: Default value that will be returned if the property can't be read

outputs:
  result:
    description: Property value

runs:
  using: node12
  main: 'dist/index.js'
